# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'inscrição', 'verbose_name_plural': 'inscrições'},
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
