# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Course_Old',
        ),
        migrations.AlterModelOptions(
            name='course_old',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
    ]
