# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_abc_to_mti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_old',
            name='speakers',
        ),
        migrations.DeleteModel(
            name='Course_Old',
        ),
    ]
